name: Backyard Pond
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Backyard Pond
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#385307'
    - '#ffeb42'
    - '#e4f0ff'
    - '#87e030'
    - '#d5af00'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
