name: Backyard Pond
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Backyard Pond
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99c4cb'
    - '#77a161'
    - '#72a1ab'
    - '#b6b9ab'
    - '#d9cbc1'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
