name: Backyard Pond
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Backyard Pond
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#142553'
    - '#756c39'
    - '#bf3d59'
    - '#fdb062'
  brandStrength: 1
  lightness: 0.9675583594944328
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
